title: Blog
description: My Personal Blog
author: Bhavik Shah
github: https://github.com/bhavikb
about: I code at Amazon.com
disqus_shortname:
google_analytics:
avatar_url: /static/img/avatar1.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/bhavik.shah.395"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/bbshah21/"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/1680256/bhavik-shah"
    - icon: fa-github
      link: "https://github.com/bhavikb"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "#"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
