# Site settings
title: Bhavik Shah's Blog 
description: "A blog"
url: "http://bhavikshah.me/"
author:
  name: "Bhavik Shah"
  email: "bhavikshah@live.in"
  url: "https://bhavikshah.me"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
#source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

plugins: [jekyll-paginate]
# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
